#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RevMobSample.Resource", IsApplication=true)]

namespace RevMobSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040005
			public const int bisque = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int black = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int khaki = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int lightblue = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int mediumaquamarine = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int skyblue = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int white = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button4 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button5 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_launcher = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int logo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int revmob = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000c
			public const int banner = 2131099660;
			
			// aapt resource value: 0x7f060000
			public const int bannerCustomSize = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int bannerSpace = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int buttonBanner = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int buttonBannerCustomSize = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int buttonChangeActivity = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int buttonHideBanner = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int buttonOpenGLActivity = 2131099659;
			
			// aapt resource value: 0x7f060001
			public const int buttons = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int hideAbsoluteBanner = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int showAbsoluteBannerOnBottom = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int showAbsoluteBannerOnTop = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int textTestInfo = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
